#spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/flight_info_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: flightService

#mybatis
mybatis:
  mapper-locations: classpath:com.flightinfosys.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    type-aliases-package: com.flightinfosys.domain
